# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 10:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='შეიქმნა')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='განახლდა')),
                ('title', models.CharField(default='', max_length=200, verbose_name='სათაური')),
                ('description', ckeditor.fields.RichTextField(default='', verbose_name='აღწერა')),
                ('image', models.FileField(null=True, upload_to='imgs', verbose_name='სურათი')),
                ('publisher', models.CharField(max_length=200, null=True, verbose_name='გამომცემლობა')),
                ('cover', models.CharField(max_length=200, null=True, verbose_name='ყდა')),
                ('page', models.IntegerField(default=1, verbose_name='გვერდი')),
                ('retail_price', models.IntegerField(default=1, verbose_name='საცალო ფასი')),
                ('catalog_price', models.IntegerField(default=1, verbose_name='კატალოგის ფასი')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='შეიქმნა')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='განახლდა')),
                ('title', models.CharField(default='', max_length=200, verbose_name='სათაური')),
                ('slug', models.SlugField(max_length=250, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
