# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170110_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='შეიქმნა')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='განახლდა')),
                ('img', models.ImageField(upload_to='slideshow_img/', verbose_name='სურათი')),
            ],
            options={
                'verbose_name_plural': 'სლაიდის სურათები',
                'verbose_name': 'სლაიდის სურათი',
            },
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='image',
            field=models.FileField(null=True, upload_to='books_img/', verbose_name='სურათი'),
        ),
    ]
