# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170111_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidemodel',
            name='title',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='სათაური'),
        ),
    ]
