# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_slidemodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CategoryModel', verbose_name='კატეგორია'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='catalog_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='კატალოგის ფასი'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='საცალო ფასი'),
        ),
    ]
