# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170112_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='შეიქმნა')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='განახლდა')),
            ],
            options={
                'verbose_name_plural': 'კალათები',
                'verbose_name': 'კალათა',
            },
        ),
        migrations.CreateModel(
            name='BasktLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='შეიქმნა')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='განახლდა')),
                ('quantity', models.IntegerField(default=1, verbose_name='რაოდენობა')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BookModel', verbose_name='წიგნი')),
            ],
            options={
                'verbose_name_plural': 'შეკვეთები',
                'verbose_name': 'შეკვეთა',
            },
        ),
        migrations.AddField(
            model_name='basketmodel',
            name='line',
            field=models.ManyToManyField(to='app.BasktLine', verbose_name='შეკვეთა'),
        ),
    ]
