# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170113_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketmodel',
            name='line',
            field=models.ManyToManyField(blank=True, to='app.BasktLine', verbose_name='შეკვეთა'),
        ),
    ]
