# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170113_1321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasktLine',
            new_name='BasketLine',
        ),
    ]
