# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170113_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='შეიქმნა')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='განახლდა')),
                ('user', models.CharField(default='', max_length=200, verbose_name='მყიდველი')),
                ('title', models.CharField(default='', max_length=200, verbose_name='მისამართი')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
