# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 14:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_ordermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'შეკვეთა', 'verbose_name_plural': 'შეკვეთები'},
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='title',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='მისამართი'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='line',
            field=models.ManyToManyField(blank=True, to='app.BasketLine', verbose_name='შეკვეთა'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='შეკვეთის დრო'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='დამკვეთი'),
        ),
    ]
