# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170114_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketline',
            options={'verbose_name': 'შეკვეთის კომპონენტი', 'verbose_name_plural': 'შეკვეთის კომპონენტები'},
        ),
    ]
