# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 15:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_auto_20170114_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketline',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='დამკვეთი'),
        ),
    ]
