# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_basketline_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='ჯამური ღირებულება '),
        ),
    ]
