# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 00:54
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_ordermodel_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadersclubModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='შეიქმნა')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='განახლდა')),
                ('about_img', models.ImageField(upload_to='about_img/', verbose_name='სურათი (ჩვენს შესახებ)')),
                ('about_content', ckeditor.fields.RichTextField(default='', verbose_name='აღწერა (ჩვენს შესახებ)')),
            ],
            options={
                'verbose_name': 'რიდერსქლაბი',
                'verbose_name_plural': 'რიდერსქლაბი',
            },
        ),
    ]
