# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(null=True, upload_to='myapp', verbose_name='სურათი'),
        ),
    ]
