# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_account_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'ექაუნთი', 'verbose_name_plural': 'ექაუნთები'},
        ),
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='myapp/palitra.jpg', upload_to='myapp', verbose_name='სურათი'),
        ),
    ]
