# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='myapp/palitra-media.jpg', upload_to='myapp', verbose_name='სურათი'),
        ),
    ]
