# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20161221_2332'),
        ('registration', '0003_auto_20161222_1644'),
    ]

    operations = [
    ]
