# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20161228_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='სქესი'),
        ),
    ]
