# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_account_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='gender',
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='myapp/palitra-media.jpg', upload_to='myapp', verbose_name='სურათი'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ემაილი'),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='სახელი'),
        ),
        migrations.AlterField(
            model_name='account',
            name='home_phone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='სახ.ტელეფონი'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='გვარი'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='მობ.ტელეფონი'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=40, unique=True, verbose_name='მეტსახელი'),
        ),
    ]
