# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170113_1254'),
        ('registration', '0011_account_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.BasketModel', verbose_name='კალათა'),
        ),
    ]
