# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_account_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.BasketModel', verbose_name='კალათა'),
        ),
    ]
