# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_addressmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.ManyToManyField(blank=True, to='registration.AddressModel', verbose_name='მისამართი'),
        ),
    ]
