# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_account_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressmodel',
            options={'verbose_name': 'მისამართი', 'verbose_name_plural': 'მისამართები'},
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='user',
            field=models.CharField(default='', max_length=20, verbose_name='პიროვნება'),
        ),
    ]
